name: CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Dry run sample workflow
        run: |
          node ./bin/orchestrator.mjs \
            --dry-run \
            --workflow sample-minimal \
            --workflows-path ./examples/workflows \
            --log ./logs/sample-minimal-dryrun.jsonl \
            --console

      - name: Real execution sample workflow
        run: |
          node ./bin/orchestrator.mjs \
            --workflow sample-minimal \
            --workflows-path ./examples/workflows \
            --exec-paths ./examples/executors \
            --log ./logs/sample-minimal-exec.jsonl \
            --console

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-logs
          path: |
            logs/*.jsonl
          if-no-files-found: warn
